In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
data=pd.read_csv("New3")

In [13]:
data.head()

,Unnamed: 0,Unnamed: 0.1,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,...,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Ever Renovate,Years Since Renovation
0,0,0,7129300520,221900.0,3,1.00,1180.0,5650.0,1.0,No,...,1180.0,0,63,98178.0,47.5112,-122.257,1340.0,5650,No,0
1,1,1,6414100192,538000.0,3,2.25,2570.0,7242.0,2.0,No,...,2170.0,400,67,98125.0,47.7210,-122.319,1690.0,7639,Yes,26
2,2,2,5631500400,180000.0,2,1.00,770.0,10000.0,1.0,No,...,770.0,0,85,98028.0,47.7379,-122.233,2720.0,8062,No,0
3,3,3,2487200875,604000.0,4,3.00,1960.0,5000.0,1.0,No,...,1050.0,910,53,98136.0,47.5208,-122.393,1360.0,5000,No,0
4,4,4,1954400510,510000.0,3,2.00,1680.0,8080.0,1.0,No,...,1680.0,0,31,98074.0,47.6168,-122.045,1800.0,7503,No,0

In [14]:
data['Sale Price'].corr(data['Flat Area (in Sqft)'])

0.7020555198830958

In [16]:
np.corrcoef(data['Sale Price'],data['Flat Area (in Sqft)'])

array([[1.        , 0.70205552],
       [0.70205552, 1.        ]])

In [20]:
data.drop(columns=['ID','Unnamed: 0','Unnamed: 0.1']).corr()

,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Years Since Renovation
Sale Price,1.000000,0.308463,0.525090,0.702056,0.089559,0.256941,0.397344,0.580654,0.605366,0.323813,-0.054034,-0.053201,0.306889,0.021508,0.585394,0.082445,0.074261
No of Bedrooms,0.308463,1.000000,0.515813,0.576628,0.031692,0.175536,0.079575,0.349223,0.477549,0.303294,-0.154113,-0.152747,-0.008708,0.129569,0.391771,0.029264,-0.007198
No of Bathrooms,0.525090,0.515813,1.000000,0.754568,0.087732,0.500776,0.187791,0.635638,0.685088,0.283798,-0.505954,-0.203968,0.024570,0.223171,0.568568,0.087226,0.003551
Flat Area (in Sqft),0.702056,0.576628,0.754568,1.000000,0.172721,0.354142,0.284678,0.705725,0.876226,0.435142,-0.318146,-0.199384,0.052538,0.240091,0.756185,0.183223,0.023503
Lot Area (in Sqft),0.089559,0.031692,0.087732,0.172721,1.000000,-0.005162,0.074668,0.102314,0.183492,0.015252,-0.053119,-0.129542,-0.085719,0.229449,0.144507,0.718527,0.013835
No of Floors,0.256941,0.175536,0.500776,0.354142,-0.005162,1.000000,0.029504,0.461368,0.524031,-0.245572,-0.489244,-0.059223,0.049692,0.125620,0.280106,-0.011204,-0.000901
No of Times Visited,0.397344,0.079575,0.187791,0.284678,0.074668,0.029504,1.000000,0.223661,0.167812,0.276974,0.053395,0.084840,0.006162,-0.078453,0.280452,0.072561,0.093546
Overall Grade,0.580654,0.349223,0.635638,0.705725,0.102314,0.461368,0.223661,1.000000,0.705153,0.145232,-0.456711,-0.185855,0.111226,0.201736,0.681362,0.107581,-0.024388
Area of the House from Basement (in Sqft),0.605366,0.477549,0.685088,0.876226,0.183492,0.524031,0.167812,0.705153,1.000000,-0.051825,-0.423848,-0.261132,-0.000819,0.343793,0.731996,0.194106,0.010491
Basement Area (in Sqft),0.323813,0.303294,0.283798,0.435142,0.015252,-0.245572,0.276974,0.145232,-0.051825,1.000000,0.133072,0.074940,0.110451,-0.144822,0.200302,0.017263,0.029158
Age of House (in Years),-0.054034,-0.154113,-0.505954,-0.318146,-0.053119,-0.489244,0.053395,-0.456711,-0.423848,0.133072,1.000000,0.346854,0.148083,-0.409515,-0.326307,-0.071016,0.203375
Zipcode,-0.053201,-0.152747,-0.203968,-0.199384,-0.129542,-0.059223,0.084840,-0.185855,-0.261132,0.074940,0.346854,1.000000,0.267013,-0.564118,-0.278982,-0.147215,0.049640
Latitude,0.306889,-0.008708,0.024570,0.052538,-0.085719,0.049692,0.006162,0.111226,-0.000819,0.110451,0.148083,0.267013,1.000000,-0.135551,0.048836,-0.086420,0.019739
Longitude,0.021508,0.129569,0.223171,0.240091,0.229449,0.125620,-0.078453,0.201736,0.343793,-0.144822,-0.409515,-0.564118,-0.135551,1.000000,0.334515,0.254428,-0.055039
Living Area after Renovation (in Sqft),0.585394,0.391771,0.568568,0.756185,0.144507,0.280106,0.280452,0.681362,0.731996,0.200302,-0.326307,-0.278982,0.048836,0.334515,1.000000,0.183188,-0.008390
Lot Area after Renovation (in Sqft),0.082445,0.029264,0.087226,0.183223,0.718527,-0.011204,0.072561,0.107581,0.194106,0.017263,-0.071016,-0.147215,-0.086420,0.254428,0.183188,1.000000,0.011289
Years Since Renovation,0.074261,-0.007198,0.003551,0.023503,0.013835,-0.000901,0.093546,-0.024388,0.010491,0.029158,0.203375,0.049640,0.019739,-0.055039,-0.008390,0.011289,1.000000

In [21]:
data.head()

,Unnamed: 0,Unnamed: 0.1,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,...,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Ever Renovate,Years Since Renovation
0,0,0,7129300520,221900.0,3,1.00,1180.0,5650.0,1.0,No,...,1180.0,0,63,98178.0,47.5112,-122.257,1340.0,5650,No,0
1,1,1,6414100192,538000.0,3,2.25,2570.0,7242.0,2.0,No,...,2170.0,400,67,98125.0,47.7210,-122.319,1690.0,7639,Yes,26
2,2,2,5631500400,180000.0,2,1.00,770.0,10000.0,1.0,No,...,770.0,0,85,98028.0,47.7379,-122.233,2720.0,8062,No,0
3,3,3,2487200875,604000.0,4,3.00,1960.0,5000.0,1.0,No,...,1050.0,910,53,98136.0,47.5208,-122.393,1360.0,5000,No,0
4,4,4,1954400510,510000.0,3,2.00,1680.0,8080.0,1.0,No,...,1680.0,0,31,98074.0,47.6168,-122.045,1800.0,7503,No,0

In [22]:
data.drop(columns=['Unnamed: 0','Unnamed: 0.1'],inplace=True)

In [23]:
data.head()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,...,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft),Ever Renovate,Years Since Renovation
0,7129300520,221900.0,3,1.00,1180.0,5650.0,1.0,No,0,Fair,...,1180.0,0,63,98178.0,47.5112,-122.257,1340.0,5650,No,0
1,6414100192,538000.0,3,2.25,2570.0,7242.0,2.0,No,0,Fair,...,2170.0,400,67,98125.0,47.7210,-122.319,1690.0,7639,Yes,26
2,5631500400,180000.0,2,1.00,770.0,10000.0,1.0,No,0,Fair,...,770.0,0,85,98028.0,47.7379,-122.233,2720.0,8062,No,0
3,2487200875,604000.0,4,3.00,1960.0,5000.0,1.0,No,0,Excellent,...,1050.0,910,53,98136.0,47.5208,-122.393,1360.0,5000,No,0
4,1954400510,510000.0,3,2.00,1680.0,8080.0,1.0,No,0,Fair,...,1680.0,0,31,98074.0,47.6168,-122.045,1800.0,7503,No,0

In [24]:
data.to_csv("New4",index=False)